# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Param": "00_core.ipynb",
         "bool_arg": "00_core.ipynb",
         "anno_parser": "00_core.ipynb",
         "args_from_prog": "00_core.ipynb",
         "call_parse": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastscript.fast.ai/"

git_url = "https://github.com/fastai/fastscript/tree/master/"

def custom_doc_links(name): return None